### PR TITLE
Update docsforge.yaml

### PR DESCRIPTION
**Pull request by erez-o**
Added source browsing. You can see the docs on it on https://help.docsforge.com/master/source-browser-settings/

I added all the keys although most are the defaults.

Try it and tell me what you think.

Cheers :)

### CODE REVIEW

**Comment by erez-o** [comment]
Sorry, closing, it looks like I accidently added other changes.
I only wanted to let you see an updated version of the docsforge.yaml file

**Comment by gennaroprota** [comment]
Hi :-)

Sorry for being a bit slow to reply.

Actually the other changes are due to me, since I force-pushed the master branch (which isn't a good thing to do, in general), so your copy diverged.

Thanks for this. I'm not sure browsing sources from within the docs is a good idea, because it may induce people to rely on implementation details. But I wanted to give it a try anyway. So I created a new branch named `docsforge_experiments` and integrated your changes in it (adding the file name extensions I'm using), but I can't see anything new in the generated documentation: [documentation from 'docsforge_experiments'](https://breath.docsforge.com/docsforge_experiments/).

What am I doing wrong?

**Comment by erez-o** [comment]
As far as I can see, you're using an unchanged yaml file. 
Source browsing is optional. it needs to be engaged, add a block to the yaml file like:

```yaml
source_browser:
  title: 'Source Browser'                         # section title
  base_url: 'source'                              # base url
  input: 'src include'                            # incldue these directories
  exclude: 'include/private'                      # exclude this directory
  filename_extensions: '.cpp .h'                  # include only these filename extension
  filename_extensions_exclude: '.txt .md'         # exclude these filename extension
```

Regarding 
> I'm not sure browsing sources from within the docs is a good idea, because it may induce people to rely on implementation details

I can tell you from my experience with 3rd party packages that in most of them I had to see the implementation of various apis to decipher both the documentation and ascertain if the implementation is fast enough for my needs. 

Problem for me was always the waste of time to actually find the implementation instead of it just being there.

But again, it's opinionated, that's why I'm leaving source browsing optional.

**Comment by gennaroprota** [comment]
You wrote:
> As far as I can see, you're using an unchanged yaml file.

Ah! :-) Thank you. DocsForge didn't ask me to select the path of the yaml file, and used the one I had specified for the primary version. May I suggest that it adjusts the path accordingly to the branch name? In my case, that would have meant changing

  https://raw.githubusercontent.com/gennaroprota/breath/master/doc/source/docsforge.yaml

to

  https://raw.githubusercontent.com/gennaroprota/breath/docsforge_experiments/doc/source/docsforge.yaml

Anyway, it works well now. I think I'll leave it enabled for the moment, at least as an additional version. Thank you so much.

**Pull request closed without merging**
